version: '3.9'
services:
  db:
    image: mysql:8.0.36
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: victor
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: rest_with_spring_boot_udemy
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - victor-network
  rest-with-spring-boot-udemy:
    image: victorkeiji/rest-with-spring-boot-udemy
    restart: always
    build: ./
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 123
    ports:
      - 80:80
    expose:
      - 80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - victor-network
networks:
  victor-network:
    driver: bridge